version: '3.2'

services: 
  python:
    image: dockerpython 
    build: ./python 
    container_name: 'DockerPython'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes: 
      - ../python:/tmp/work